config/routes.rb
Boilerplate::Application.routes.draw do
  resources :users, :only => [:create, :new, :show] do
    collection do
      match 'search', :via => [:get]
    end
  end
  
  resources :friendships, :only => [:create, :new, :destroy, :index] do
    collection do
      match 'requests', :via => [:get]
    end
  end
  
  resource :session, :only => [:create, :destroy, :new]
  resource :root
  
  root :to => "roots#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :accepter, :sender, :status
  
  belongs_to :accepter,
  :class_name => "User",
  :foreign_key => :accepter
  
  belongs_to :requests,
  :class_name => "User", 
  :foreign_key => :sender
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :latitude, :longitude

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username
  attr_reader :password

  has_one :location
  
  has_many :requests, :through => :requests_join
  
  has_many :requests_join,
  :class_name => "Friendship",
  :foreign_key => :accepter,
  :conditions => { :status => false }

  validates :username, :presence => true
  validates :username, :uniqueness => true
  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def self.search_by_name(query)
    results = []
    intermediary = []
    return results if query.empty?
    users = User.all
    query = query.downcase
    
    users.sort {|u1, u2| u1.username <=> u2.username }.each do |user|
      name = user.username
      if name.start_with?(query)
        results << {:id => user.id, :name => name}
      elsif name.include?(query)
        intermediary << {:id => user.id, :name => name}
      end
    end
    
    results += intermediary
  end
      
  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    
  end
  
  def new
    accepter = params[:id]
    @friendship = Friendship.create(sender: current_user.id, 
                                    accepter: accepter,
                                    status: false)
                                    
    render :json => @friendship, :status => 200
  end
  
  def destroy
    
  end
  
  def requests
    @requests = Friendship.find_all_by_accepter_and_status(current_user.id, false)
    
    @requests.map! { |user| [user.id, user.username, user.updated_at] }
    
    render :json => @requests, :status => 200
  end
  
end

app/controllers/roots_controller.rb
class RootsController < ApplicationController
  
  before_filter :require_current_user!
  
  def show
    render 'show'
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]
  
  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    
    if @user.nil?
      flash.now[:errors] = ["Credentials were wrong"]
      @user = User.new(:username => params[:user][:username])
      render "new"
    else
      self.current_user = @user
      redirect_to root_url
    end
  end
  
  def destroy
    logout_current_user!
    redirect_to new_session_url
  end
  
  def new
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      self.current_user = @user
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render "new"
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end
  
  def search
    users = User.search_by_name(params[:text])
    
    render :json => users, :status => 200 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end
  
  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end
  
  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end
  
  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zegla</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Zegla</a>
    </div>
    
    <% if current_user %>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <div class="form">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" size="40" placeholder="Search for friends">
        </div>
      </form>
      <div class="names"></div>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.username %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Edit Account</a></li>
            <li><a href="<%= session_url %>" data-method="delete">Log out</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <% end %>
  </nav>
  
    
<% if flash.now[:errors] %>
  <ul>
    <% flash.now[:errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/roots/show.html.erb
<div class="coords"></div>
<br>
<div class="requests"></div>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text"
     value= "<%= user.username %>">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" class="btn btn-primary" value="<%= message %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, user!</p>